name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unique
        run: |
          x=$(jq 'map(.name + .network + .branch + .specVersion)' templates.json)
          y=$(jq 'length' <<< "$x")
          z=$(jq 'unique | length' <<< "$x")
          [ $y == $z ]
