name: test
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unique
        run: |
          set -xo pipefail
          x=$(jq 'map(.name + .branch + .specVersion)' templates.json)
          y=$(jq 'length' <<< "$x")
          z=$(jq 'unique | length' <<< "$x")
          [ $y == $z ]
